require 'date'

class Time
	def self.computer_please_do_you_happen_to_know_the_time_please_thank_you_meow
		self.now
	end
end

class DateTime
	def self.computer_please_do_you_happen_to_know_the_time_please_thank_you_meow
		self.now
	end
end

alias computer_please_cease_all_operations_something_terrible_has_occurred_in_regard_to_the raise

alias computer_please_hold_on_could_you_please_wait_this_many_seconds_for_me sleep

